export const attribute3Schema = {
  success: true,
  attribute: {
    id: 'attr-3',
    code: '3',
    title: 'Attribute 3: Infrastructure and Learning Resources',
    description: 'Physical facilities, library expenditure, research software, IT infrastructure, and inclusive campus environment.',
    version: 1,
    active: true,
    sections: [
      {
        id: 'sec-3-1',
        code: '3.1',
        title: 'Physical Infrastructure & Facilities',
        description: 'Teaching classrooms, specialized laboratories, campus sports, and student amenities.',
        displayOrder: 1,
        fields: [
          {
            id: 'f-3-1-1',
            code: '3.1.1',
            label: 'Teaching Classrooms',
            description: 'Total number of fully operational teaching classrooms available for curriculum delivery.',
            fieldType: 'NUMBER',
            unit: 'Classrooms',
            required: true,
            proofRequired: true,
            remarksAllowed: true,
            displayOrder: 1,
            validationRules: JSON.stringify({ min: 0 }),
          },
          {
            id: 'f-3-1-2',
            code: '3.1.2',
            label: 'Laboratories',
            description: 'Dedicated academic and practical experimental laboratories.',
            fieldType: 'NUMBER',
            unit: 'Laboratories',
            required: true,
            proofRequired: true,
            remarksAllowed: true,
            displayOrder: 2,
            validationRules: JSON.stringify({ min: 0 }),
          },
          {
            id: 'f-3-1-3',
            code: '3.1.3',
            label: 'Hostel Facility',
            description: 'On-campus student accommodation units. Toggle Not-Applicable if non-residential.',
            fieldType: 'NUMBER',
            unit: 'Hostels',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 3,
            validationRules: JSON.stringify({ min: 0, allowNA: true }),
          },
          {
            id: 'f-3-1-4',
            code: '3.1.4',
            label: 'Canteen Facility',
            description: 'Hygiene-certified campus food and dining facilities.',
            fieldType: 'NUMBER',
            unit: 'Canteens',
            required: true,
            proofRequired: true,
            remarksAllowed: true,
            displayOrder: 4,
            validationRules: JSON.stringify({ min: 0 }),
          },
          {
            id: 'f-3-1-5',
            code: '3.1.5',
            label: 'Sports Ground',
            description: 'Outdoor athletic grounds and multipurpose play fields.',
            fieldType: 'NUMBER',
            unit: 'Grounds',
            required: true,
            proofRequired: true,
            remarksAllowed: true,
            displayOrder: 5,
            validationRules: JSON.stringify({ min: 0 }),
          },
          {
            id: 'f-3-1-6',
            code: '3.1.6',
            label: 'Separate Clean Washroom – Boys',
            description: 'Dedicated functional and sanitized washrooms for male students.',
            fieldType: 'NUMBER',
            unit: 'Units',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 6,
            validationRules: JSON.stringify({ min: 0 }),
          },
          {
            id: 'f-3-1-7',
            code: '3.1.7',
            label: 'Separate Clean Washroom – Girls',
            description: 'Dedicated functional and sanitized washrooms for female students.',
            fieldType: 'NUMBER',
            unit: 'Units',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 7,
            validationRules: JSON.stringify({ min: 0 }),
          },
          {
            id: 'f-3-1-8',
            code: '3.1.8',
            label: 'Portable Drinking Water Facility',
            description: 'RO/UV purified drinking water dispensing stations on campus.',
            fieldType: 'NUMBER',
            unit: 'Stations',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 8,
            validationRules: JSON.stringify({ min: 0 }),
          },
          {
            id: 'f-3-1-9',
            code: '3.1.9',
            label: 'Language Laboratory',
            description: 'Computer-aided language and communication laboratory setups.',
            fieldType: 'NUMBER',
            unit: 'Labs',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 9,
            validationRules: JSON.stringify({ min: 0, allowNA: true }),
          },
          {
            id: 'f-3-1-10',
            code: '3.1.10',
            label: 'Auditorium and Seminar Halls',
            description: 'Audio-visual equipped conference halls and institutional auditorium.',
            fieldType: 'NUMBER',
            unit: 'Halls',
            required: true,
            proofRequired: true,
            remarksAllowed: true,
            displayOrder: 10,
            validationRules: JSON.stringify({ min: 0 }),
          },
          {
            id: 'f-3-1-11',
            code: '3.1.11',
            label: 'Gymnasium',
            description: 'Campus fitness center with physical training equipment.',
            fieldType: 'NUMBER',
            unit: 'Gyms',
            required: true,
            proofRequired: true,
            remarksAllowed: true,
            displayOrder: 11,
            validationRules: JSON.stringify({ min: 0 }),
          },
          {
            id: 'f-3-1-12',
            code: '3.1.12',
            label: 'Health & Wellness Centre',
            description: 'First-aid, emergency medical room, and wellness counseling facility.',
            fieldType: 'NUMBER',
            unit: 'Centres',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 12,
            validationRules: JSON.stringify({ min: 0 }),
          },
          {
            id: 'f-3-1-13',
            code: '3.1.13',
            label: 'Guest House',
            description: 'Accommodations for visiting professors, experts, and examiners.',
            fieldType: 'NUMBER',
            unit: 'Units',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 13,
            validationRules: JSON.stringify({ min: 0, allowNA: true }),
          },
          {
            id: 'f-3-1-14',
            code: '3.1.14',
            label: 'Transportation Facilities',
            description: 'Institutional buses, vans, and transit shuttles.',
            fieldType: 'NUMBER',
            unit: 'Vehicles',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 14,
            validationRules: JSON.stringify({ min: 0, allowNA: true }),
          },
          {
            id: 'f-3-1-15',
            code: '3.1.15',
            label: 'Museum / Artifacts',
            description: 'Historical, botanical, geological, or heritage preservation collections.',
            fieldType: 'NUMBER',
            unit: 'Collections',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 15,
            validationRules: JSON.stringify({ min: 0, allowNA: true }),
          },
        ]
      },
      {
        id: 'sec-3-2',
        code: '3.2',
        title: 'Library & Digital Learning Resources Expenditure',
        description: 'Annual expenditure on e-books, e-journals, digital databases, and overall institutional non-salary expenditure.',
        displayOrder: 2,
        fields: [
          {
            id: 'f-3-2-1a',
            code: '3.2.1a',
            label: 'Expenditure on e-books and digital resources',
            description: 'Direct annual financial expenditure on digital library books, journals, and databases (in INR ₹).',
            fieldType: 'CURRENCY',
            unit: 'INR (₹)',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 1,
            validationRules: JSON.stringify({ min: 0 }),
          },
          {
            id: 'f-3-2-2',
            code: '3.2.2',
            label: 'Total expenditure excluding salary',
            description: 'Total institutional annual recurring and capital expenditure, excluding staff salaries (in INR ₹).',
            fieldType: 'CURRENCY',
            unit: 'INR (₹)',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 2,
            validationRules: JSON.stringify({ min: 0 }),
          },
          {
            id: 'f-3-2-1',
            code: '3.2.1',
            label: 'Percentage expenditure on e-books and digital resources',
            description: 'Calculated as: (Expenditure on digital resources / Total expenditure excluding salary) * 100.',
            fieldType: 'PERCENTAGE',
            unit: '%',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 3,
            validationRules: JSON.stringify({ formula: 'percentage_of_total', numeratorField: '3.2.1a', denominatorField: '3.2.2' }),
          },
        ]
      },
      {
        id: 'sec-3-3',
        code: '3.3',
        title: 'Research Facilities, Software & Consortia Subscriptions',
        description: 'Subscriptions to national/international research consortia, specialized software, and departmental research labs.',
        displayOrder: 3,
        fields: [
          {
            id: 'f-3-3-1',
            code: '3.3.1',
            label: 'E-Journals Consortia subscription',
            description: 'Active membership to national consortia (e.g. N-LIST, DELNET, IEEE, ScienceDirect).',
            fieldType: 'TEXT',
            unit: 'Consortia Name',
            required: true,
            proofRequired: true,
            remarksAllowed: true,
            displayOrder: 1,
            validationRules: JSON.stringify({ suggestedValues: ['N-LIST', 'DELNET', 'INFLIBNET', 'None'] }),
          },
          {
            id: 'f-3-3-2',
            code: '3.3.2',
            label: 'Subscription to e-Shodh Sindhu',
            description: 'Higher education research resources consortium subscription status.',
            fieldType: 'TEXT',
            unit: 'Status / Membership',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 2,
            validationRules: JSON.stringify({ suggestedValues: ['N-LIST', 'Active', 'None', '-----'] }),
          },
          {
            id: 'f-3-3-3',
            code: '3.3.3',
            label: 'Plagiarism Checking Software',
            description: 'Licensed academic similarity & integrity software (e.g., Turnitin, DrillBit, Urkund).',
            fieldType: 'TEXT',
            unit: 'Software Name',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 3,
            validationRules: JSON.stringify({ suggestedValues: ['Turnitin', 'DrillBit', 'Ouriginal/Urkund', '-----'] }),
          },
          {
            id: 'f-3-3-4',
            code: '3.3.4',
            label: 'Licensed Statistical Software',
            description: 'Statistical analysis software packages (e.g. SPSS, SAS, Stata, R-Studio Pro).',
            fieldType: 'TEXT',
            unit: 'Software Name',
            required: false,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 4,
            validationRules: JSON.stringify({}),
          },
          {
            id: 'f-3-3-5',
            code: '3.3.5',
            label: 'Discipline-Specific Software',
            description: 'Engineering, architectural, bioinformatics or design software (e.g., MATLAB, AutoCAD, ChemDraw).',
            fieldType: 'TEXT',
            unit: 'Packages',
            required: false,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 5,
            validationRules: JSON.stringify({}),
          },
          {
            id: 'f-3-3-6',
            code: '3.3.6',
            label: 'Discipline-Specific Research Laboratories',
            description: 'Specialized high-end departmental research and incubation spaces.',
            fieldType: 'TEXT',
            unit: 'Facilities',
            required: false,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 6,
            validationRules: JSON.stringify({}),
          },
          {
            id: 'f-3-3-7',
            code: '3.3.7',
            label: 'Other Relevant Research Resources',
            description: 'Repositories, specialized databases, patent archives, or instrumentation facilities.',
            fieldType: 'TEXT',
            unit: 'Resources',
            required: false,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 7,
            validationRules: JSON.stringify({}),
          },
        ]
      },
      {
        id: 'sec-3-4',
        code: '3.4',
        title: 'IT Infrastructure & Digital Campus',
        description: 'Campus internet bandwidth, student-to-computer ratio, device availability, and digital learning setups.',
        displayOrder: 4,
        fields: [
          {
            id: 'f-3-4-1',
            code: '3.4.1',
            label: 'Internet Bandwidth in MBPS',
            description: 'Dedicated leased line internet bandwidth available across the institution.',
            fieldType: 'NUMBER',
            unit: 'MBPS',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 1,
            validationRules: JSON.stringify({ min: 1 }),
          },
          {
            id: 'f-3-4-2',
            code: '3.4.2',
            label: 'Student-to-Computer Ratio',
            description: 'Calculated ratio based on total enrolled students to total functional student computers (e.g. 1:16 with 4,127 students).',
            fieldType: 'RATIO',
            unit: 'Ratio (Students : Computers)',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 2,
            validationRules: JSON.stringify({ formula: 'ratio', relatedComputerField: '3.4.3' }),
          },
          {
            id: 'f-3-4-3',
            code: '3.4.3',
            label: 'Number of Laptops / Desktop available for students',
            description: 'Total working desktop computers and laptops exclusively allocated for student academic use.',
            fieldType: 'NUMBER',
            unit: 'Computers',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 3,
            validationRules: JSON.stringify({ min: 0 }),
          },
          {
            id: 'f-3-4-4',
            code: '3.4.4',
            label: 'Advanced Digital Facilities',
            description: 'State-of-the-art immersive technologies such as Virtual Classrooms & Laboratories, AR/VR setups.',
            fieldType: 'MULTI_SELECT',
            unit: 'Facilities',
            required: false,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 4,
            validationRules: JSON.stringify({
              options: [
                'Virtual Classrooms and Laboratories',
                'Augmented Reality (AR) & Virtual Reality (VR)',
                'AI/Robotics Lab',
                'Media Center / Recording Studio',
              ],
            }),
          },
        ]
      },
      {
        id: 'sec-3-5',
        code: '3.5',
        title: 'Barrier-Free Campus & Divyangjan (PwD) Accessibility',
        description: 'Ramps, lifts, accessible washrooms, assistive technologies (e.g. JAWS), and human assistance facilities.',
        displayOrder: 5,
        fields: [
          {
            id: 'f-3-5-1',
            code: '3.5.1',
            label: 'Built environment with Ramps / Lifts',
            description: 'Architectural barrier-free access with step-free entrance ramps, handrails, and passenger elevators.',
            fieldType: 'BOOLEAN',
            unit: 'Yes/No',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 1,
            validationRules: JSON.stringify({}),
          },
          {
            id: 'f-3-5-2',
            code: '3.5.2',
            label: 'Divyangjan-friendly washrooms',
            description: 'Dedicated accessible toilets with grab-bars, wide doors, and wheelchair turning space.',
            fieldType: 'NUMBER',
            unit: 'Washrooms',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 2,
            validationRules: JSON.stringify({ min: 0 }),
          },
          {
            id: 'f-3-5-3',
            code: '3.5.3',
            label: 'Tactile Paths / Appropriate Lighting and Display Boards / Signposts',
            description: 'Guiding tactile ground surface indicators (TGSI), LED directional signage, and high-contrast signage.',
            fieldType: 'BOOLEAN',
            unit: 'Yes/No',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 3,
            validationRules: JSON.stringify({}),
          },
          {
            id: 'f-3-5-4',
            code: '3.5.4',
            label: 'Assistive technology and facilities for Persons with Disabilities',
            description: 'Accessible websites, screen-reading software (e.g. JAWS, NVDA), mechanized braille/speech equipment.',
            fieldType: 'TEXT',
            unit: 'Assistive Tools',
            required: true,
            proofRequired: true,
            remarksAllowed: true,
            displayOrder: 4,
            validationRules: JSON.stringify({ suggestedValues: ['JAWS', 'NVDA', 'Braille Embosser', 'None'] }),
          },
          {
            id: 'f-3-5-5',
            code: '3.5.5',
            label: 'Provision of enquiry and Information: Human Assistant and Softcopies of reading materials',
            description: 'Designated helpdesk assistants, accessible digital audio/e-texts, and scribes for examinations.',
            fieldType: 'BOOLEAN',
            unit: 'Yes/No',
            required: true,
            proofRequired: false,
            remarksAllowed: true,
            displayOrder: 5,
            validationRules: JSON.stringify({}),
          },
        ]
      }
    ]
  },
  years: [
    { id: 'y-2023-24', code: '2023-24', displayOrder: 1 },
    { id: 'y-2024-25', code: '2024-25', displayOrder: 2 },
    { id: 'y-2025-26', code: '2025-26', displayOrder: 3 },
  ]
};
